### ISSUE TITLE
Cannot look at removed comments in log

### ISSUE THREAD

**Issue by willwoodlief** [toolbox-team/reddit-moderator-toolbox#106]
My browser has an error when looking at https://www.reddit.com/r/subreddit/about/log/?mod=

and I press the 'load text of removed comments' button

```
modmatrix.js:741 Uncaught TypeError: TBUtils.getJSOIN is not a function
    at getComments (modmatrix.js:741)
    at HTMLAnchorElement.<anonymous> (modmatrix.js:776)
    at HTMLBodyElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLBodyElement.y.handle (jquery-3.3.1.min.js:2)
```

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/b3e7442e28f64c1d0f547a4601d1ba12622117b0/extension/data/modules/modmatrix.js#L741

I think its a typo with i added in json

**Comment by creesch** [comment]
Thank you, can confirm that it indeed should be `JSON`, we'll fix it.
