### ISSUE TITLE
Instances of hacky 'new.reddit' subdomain usage.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#11]
_From @creesch on August 22, 2017 20:11_

Initially we cannot escape some hacky stuff to get it to work on the `new.reddit` subdomain. Obviously this will need to be fixed at a later date. This issue attempts to keep track of those instances.

---

- [x] `tbmodule.js`  https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/extension/data/tbmodule.js#L385

    `if (TB.storage.domain !== 'new' && TB.storage.domain !== 'www') {`

- [ ] `tbutils.js` https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/blob/master/extension/data/tbutils.js#L63

    ``TBUtils.tempBaseDomain = window.location.hostname === 'new.reddit.com' ? 'https://new.reddit.com' : 'https://www.reddit.com';``

_Copied from original issue: Geo1088/reddit-moderator-toolbox#1_

**Comment by Geo1088** [comment]
Updated line references and code snippets, `alpha.reddit` -> `new.reddit`

**Comment by Geo1088** [comment]
`TBUtils.tempBaseDomain` seems to be unused. After we're done hotfixing 5.0, I'm going to remove it and close this issue.
