### ISSUE TITLE
Mod button, etc. sometimes don't show up in modmail threads

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#113]

**Comment by creesch** [comment]
Whut? I am not entirely sure what the title means? Mod button always show up in modmail (new modmail that is). So if they are not showing up something else is going on.

**Comment by Geo1088** [comment]
You're right, that's not the issue. It doesn't appear to be consistent - I'll have to debug the next time it comes up. I'll change the title to reflect that.

**Comment by creesch** [comment]
Also related to #38

**Comment by Geo1088** [comment]
Closing since I've never actually been able to repro this and hopefully #38 will take care of any bugs in this system.
