### ISSUE TITLE
Queue tools modqueue filter threshold only applies when using the keyboard

### ISSUE THREAD

**Issue by adzm** [toolbox-team/reddit-moderator-toolbox#122]
Browser name: Chrome
Browser version: Chrome 76
Module: Queue Tools
Issue location: Modqueue
Issue description: Changing the report filter threshold only applies when using the keyboard; changing with the mouse or accessibility tools do not trigger the keypress event.

**Comment by adzm** [comment]
Created a pull request, #121

**Comment by Geo1088** [comment]
Closed with #121 and b89f896
