### ISSUE TITLE
Mod mail loaded in: NaN seconds

### ISSUE THREAD

**Issue by fungiboletus** [toolbox-team/reddit-moderator-toolbox#138]
Using Microsoft Edge Dev (yes) and the chromium reddit-moderator-toolbox, on the modmail I get the following message : « mod mail loaded in: NaN seconds ».

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/b3e7442e28f64c1d0f547a4601d1ba12622117b0/extension/data/modules/modmailpro.js#L692

**Comment by Geo1088** [comment]
Can you reproduce in Chrome or Firefox?

**Comment by k3n** [comment]
I can take a look but can't repro. myself.

**Comment by creesch** [comment]
This is in old modmail and probably a result of a `var` converted to a `let` in the wrong scope
