### ISSUE TITLE
"open in old Reddit" button doesn't update its href when navigating different pages on new Reddit

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#142]
The current code sets the `href` of the link once when the page loads, but since new reddit is a SPA that updates `window.location` without reloading the page, the button still points to the initial page unless the browser is reloaded manually.

Ideally we can still keep the button as a link, because that makes middle-clicking work, and instead just update the `href` when we get a page navigation event from the jsapi.

**Comment by creesch** [comment]
fyi we already have a mechanism that sends an event to all of toolbox when the href changes. So it should be easy to update.
