### ISSUE TITLE
Removal Reasons will not show up if clicking "Confirm Removal" on new reddit

### ISSUE THREAD

**Issue by Newcool1230** [toolbox-team/reddit-moderator-toolbox#146]
For new reddit there is a new button called "Confirm Removal". Removal reason on toolbox will not show up unless you approve the post first them remove it.

**Comment by creesch** [comment]
I tried to find this button but I can't seem to find it. If I remove stuff on new reddit it simply removes them and removal reasons show up. Is this something that needs to be enabled somewhere?

**Comment by creesch** [comment]
nvm found it, this happens for filtered stuff in queues.
