### ISSUE TITLE
bug(Modbar): New Modmail count includes highlighted

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#162]
Right now it includes highlighted, which will be added to the count with in progress, or new and will thus report twice. 

This is one modmail, not two
![image](https://user-images.githubusercontent.com/6598829/66524153-e31f2d80-eaf1-11e9-95a0-9a4a19435415.png)

**Comment by creesch** [comment]
Technically correct I guess :P
