### ISSUE TITLE
Don't open modmail in new tab when already in modmail on clicking modmail icon in modbar.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#167]
Title

**Comment by k3n** [comment]
I think the first case is what's explicitly asked for, but what about the tooltips to the other views? It would seem like one would want it to not open a new tab for a view you're already on.

* if on `/mail/all` and I click modmail, refresh
* if on `/mail/new`  and I click "New", refresh
* etc.

Does that sound right?

**Comment by Geo1088** [comment]
I think all that needs to be done here is change `openMailTab` to `false` when the domain is `mod.reddit.com`. That would cover everything at once. https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/modbar.js#L132
