### ISSUE TITLE
Modlog matrix: From/to date input matching is very strict

### ISSUE THREAD

**Issue by rasher** [toolbox-team/reddit-moderator-toolbox#176]
If I enter, eg "2014-05-1" as the from date, it searches right back to the beginning of the data. My theory is that it's looking for the string 2014-05-1, which never comes (instead 2014-05-01 does). Maybe some simple validation could be added, or the date could parsed more intelligently, or a date-picker widget could be used. Or maybe it's something else entirely :)

**Comment by creesch** [comment]
Closing this as most browsers these days have a date picker there.
