### ISSUE TITLE
Race condition in new modmail

### ISSUE THREAD

**Issue by k3n** [toolbox-team/reddit-moderator-toolbox#181]
This manifests itself as an error in the console:

```js
Uncaught TypeError: Cannot read property '1' of null
    at Object.TBUtils.getThingInfo(tbutils.js: 1496)
    at addNewMMMacro(macros.js: 144)
    at macros.js: 235
```

Though no actual adverse side-effects are observed, it's best not to have stuff show up in the console.

Repro:

1. nav to new modmail
1. click into a thread
1. _quickly_ click `<` to return to the index
1. observe above error in console*

_\* only appears in Chrome, even though FF also produces the same error condition; I don't use FF much so I'm not sure what's going on, as it seems it should also throw an error._

Seems to be caused by the `idRegex` of `/.*mod.reddit.com/mail/.*?/(.*?)$/i` trying to match the current URL, which under the above repro steps, will simply be `https://mod.reddit.com/mail/notifications` which causes the regex to fail and the ensuing reference to the `[1]` element of the match to throw the error.

**Comment by creesch** [comment]
> I don't use FF much so I'm not sure what's going on, as it seems it should also throw an error.

That is a sort of bug firefox has with extension content_scripts. Thrown errors get lost somewhere in a sandboxing layer of sorts. 

Anyway, as I said in discord we might want to just simply try catch this specific bit of code as it would be a pain to properly address and doesn't have a negative effect on functionality.

**Comment by k3n** [comment]
Would you be open to a solution that doesn't use try/catch? I have one that appears to work and it's really simple. I can PR if you want to see the details. I just generally try to avoid try/catch.

**Comment by creesch** [comment]
Sure, like I said as long as it doesn't make things complicated elsewhere.
