### ISSUE TITLE
build-watch may clear manifest.json file when saving often

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#205]
If I run `build-watch` and save a file right after saving again, there is a chance that the script nodemon runs will cancel and start anew. This has caused manifest.json on numerous occasions to simply be wiped clean of content

**Comment by Geo1088** [comment]
I've been having this issue a lot lately, we may want to copy the modified file into the build directory and work from there rather than modifying it in place.

**Comment by creesch** [comment]
I am guessing this is no longer an issue given we don't use nodemon anymore :)
