### ISSUE TITLE
Make the "show ignored reports" feature actually work. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#207]
https://www.reddit.com/r/toolbox/comments/ec8o01/viewing_ignored_reports_appears_to_be_broken/

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbapi.js#L656

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/4bf794a2e942e21b1706aaebee0a9f75baadfe6b/extension/data/modules/queuetools.js#L262

Needs to make use `user_reports_dismissed`.

**Comment by justcool393** [comment]
one thing of note is that the `user_reports` and `mode_reports` fields are still useful for viewing non-dismissed ignored reports (i.e. reports when the post hasn't been approved since the ignoring of the reports).

i don't know why it gets the object incorrectly

**Comment by Geo1088** [comment]
Wow, `getReportReasons` is just totally broken. The normalized URL of comments pages contains a trailing slash, so the following line will try to fetch a `/.json` page which will never work.

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/310e24350a5308d0031e758c8bda624e3793b4d9/extension/data/tbapi.js#L689

Also, it contains a check for `callback` even though it returns a Promise, so even if the request succeeded it would never return any value.

I can try to clean this up.

**Comment by creesch** [comment]
`/.json` is actually fine in the context of reddit. https://old.reddit.com/.json will just work fine.
