### ISSUE TITLE
Queue tools: Expand searching to apply to multiple fields

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#218]
This has to be a simple fix, it's kinda a wonder nobody's complained about it before.

**Comment by creesch** [comment]
Probably because barely anyone uses that functionality :P I had to double check as at first I wasn't sure what the issue was about.

**Comment by creesch** [comment]
Oooh... now that I think about it "select by post ID" would be cool as well.

**Comment by creesch** [comment]
Sorry for the comment spam, I think this should apply to all items there. So also domain, user and title. 


A neat QoL improvement would be to provide a selection list of all possible items on page like we currently do with user search input.

**Comment by Geo1088** [comment]
Yeah, that sounds like a good idea. Just throw it all in a generic "select by search" option and then write up a little static window that has a text field and checkboxes for subreddit, title, body, URL, author, etc.

**Comment by creesch** [comment]
Something like that yeah, giving it a proper interface. Not sure if we want just one input field or leave it like it is now.

**Comment by creesch** [comment]
A bit like this (domain)
![image](https://user-images.githubusercontent.com/2502190/74317501-d2224980-4d7b-11ea-8959-63d342e34eab.png)

And then when typing have the suggestion thing pop up like so 

![image](https://user-images.githubusercontent.com/2502190/74317599-05fd6f00-4d7c-11ea-81da-cab1f63ecfd1.png)

**Comment by SpyTec** [comment]
For this feature to be good, all of these in red need to be changed to have consistency 

![image](https://user-images.githubusercontent.com/6598829/75607397-0ecd9f00-5af7-11ea-8bf5-9cbf031f28da.png)

**Comment by creesch** [comment]
Additional suggestion [report reason selection](https://www.reddit.com/r/toolbox/comments/fdyqjd/filter_modqueue_by_report_reason/).

**Comment by creesch** [comment]
> Ideally we shouldn't have a bunch of inputs in dropdowns

Well I have been thinking that instead of a dropdown we make use of a popup when the select button is clicked. Giving us enough space and UI utility to give people proper options. 

Basically like a search engine advanced search options for narrowing down a search result. 
 
![image](https://user-images.githubusercontent.com/2502190/76009123-fc959b80-5f10-11ea-8c4c-3b19c4eead75.png)

**Comment by SpyTec** [comment]
Having a click to expand panel sort of thing would be possible as well, means we can have real-time results without having to do a pop-up every time. Makes it easier to do quick searches without getting a popup every time

To see what I mean, look at https://www.patternfly.org/v4/documentation/react/components/datatoolbar#component-managed-toggle-groups in a medium viewport, filter button will be there which expands a panel when clicked

**Comment by creesch** [comment]
But that requires us to build an UI element we currently don't have. Which is possible but then I'd like to understand the advantage a bit more. I am also not entirely sure how that would allow for the variety of options we have now. 

What I currently have in mind would be more along the lines of this 

![image](https://user-images.githubusercontent.com/2502190/76010334-01f3e580-5f13-11ea-88aa-28a00398c52a.png)


But then not ugly and functional ;) It also does allow us to explain some options better in line as some of these things only make sense for people that have modded long enough to know all the reddit mod terminology.
