### ISSUE TITLE
Removal Reason settings per subreddit

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#219]
There's a few things we currently have user-side that could also exist in subreddit settings.

- [ ] Sticky removal message
- [ ] Lock removal message
- [ ] Remove as comment/PM/Modmail
- [x] Enable/Disable removal reason for posts (#224)
- [x] Enable/Disable removal reason for comments (#224)

**Comment by creesch** [comment]
I thought we did discuss this already at some point, I guess we didn't make an issue for it at the time? 

Additional question to figure out: 

- If a subreddit has set a specific configuration should the individual mod still be able to overwrite it? (for example, still send through modmail). 
- If not, should we provide it as a explicit setting "`allow mods to override subreddit`"?

**Comment by creesch** [comment]
Also:

> Allow/Disallow removal reason for posts
> Allow/Disallow removal reason for comments

Shouldn't these be enable/disable? Should we consider requiring at least one to be active?

**Comment by SpyTec** [comment]
> I thought we did discuss this already at some point, I guess we didn't make an issue for it at the time?
We did, couldn't find an issue about it

> Additional question to figure out:
> 
>     * If a subreddit has set a specific configuration should the individual mod still be able to overwrite it? (for example, still send through modmail).
>     * If not, should we provide it as a explicit setting "`allow mods to override subreddit`"?
I'd say yes, we should only pre-select the values. Though if mods really want to disallow certain actions we could add another setting for disabling actions. Such as remove as PM or modmail.



> Also:
> 
> > Allow/Disallow removal reason for posts
> > Allow/Disallow removal reason for comments
> 
> Shouldn't these be enable/disable? Should we consider requiring at least one to be active? Because disabling both effectively turns of removal reasons which I can already see resulting in us getting odd support requests.
Right, yes. That's what I meant :D

**Comment by Geo1088** [comment]
>  Enable/Disable removal reason for posts
>  Enable/Disable removal reason for comments

I'd much rather see these as settings per-removal reason than per-sub, and not allow the user to override them. The "no reason" button will always exist and there's no good reason for mods to blanket ignore removal reasons if the team took the time to set them up. Some removal reasons apply to comments but not posts, and this system would provide better flexibility.

>  Sticky removal message
>  Lock removal message
>  Remove as comment/PM/Modmail

To be honest, I think if the sub sets these settings there should be no way to set a permanent override as a user. Case-by-case overrides are useful, but there should be some sort of confirmation if the mod wants to go against the prescribed settings. Personal equivalents of these settings should only be used if the sub config doesn't have any preference.

**Comment by SpyTec** [comment]
If we introduce removal reasons for posts/comments. Should the default for all existing RR be true for posts, false for comments?

If so, what should happen to people who have show RR for comments enabled? Nothing?

Or should we rather do a check in that if a RR doesn't have the field, show it for people who have show RR for comments, but don't show it for people who don't have it enabled?

**Comment by Geo1088** [comment]
Part of me wants to say we should just ditch the personal setting entirely, and default everything to apply to both posts and comments. Not sure how much of an impact that would really have, but I'm guessing a fair amount of subs already have all their mods enable removal reasons for comments anyway.

**Comment by creesch** [comment]
> and default everything to apply to both posts and comments.

I am willing to bet that the majority of subreddits doesn't do removal reasons for comments so I rather not enable it there by default.
