### ISSUE TITLE
Usernotes manager performs badly

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#221]
Just fix all of it tbh, labeling as a bug because it basically makes the usernotes page unusable for subs that are near the limit.

**Comment by SpyTec** [comment]
Define fix all of it

**Comment by creesch** [comment]
I am fairly sure geo means user note manager https://github.com/toolbox-team/reddit-moderator-toolbox/pull/223

**Comment by Geo1088** [comment]
Right, updated issue to be more clear, sorry about that
