### ISSUE TITLE
Unify markup/classes for dialogs/windows/notifications

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#240]
As it is now, all three of these are basically the same thing visually with slight differences:

- Windows are popups with an overlay background and a larger header/tab size
- Notifications are popups with `position: static`, no draggability, and no footer

By combining these to use the same base class with modifying classes for their differences, we can clean up a lot of the existing CSS. They already share [a lot of the same code](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/styles/tbui.css#L1-L94).

I propose we use `tb-window` as the base class for these, `tb-window-free` as a modifier for free (draggable) popups, and `tb-window-large` as a modifier for windows with larger headers, tabs, and footers. This would mean:

- `TBui.popup` would return a `.tb-window.tb-window-free` for a small, draggable window, 
- `TBui.overlay` would use a `.tb-window.tb-window-large` for a large, non-draggable window, and
- `TBui.showNotification` would use a `.tb-window` with no modifier classes for a small, static, non-draggable window.

Classes for sub-elements of these structures (`tb-popup-content`, etc.) would be merged into single `tb-window-*` classes, and any styles that need to apply to only a single class of window can be refactored around that.

~~Additionally, currently there are more or less two types of draggable window: absolutely positioned (move with page scroll, e.g. usernotes) and fixed positioned (don't move on scroll, e.g. personal notes). We should eliminate one or the other for a more consistent user experience, and I'm leaning towards keeping everything fixed-position to avoid issues with users losing windows by scrolling around.~~ Deemed not worth it for the small amount of complexity this adds, and is mostly a matter of preference.

Also, tab display for popups and overlays is currently different, with the latter defaulting to displaying tabs as a vertical list on the left of the window. To implement this proposal, the default tab arrangement for overlays will have to be changed to horizontal to match popups, and an additional `tb-window-vertical-tabs` helper class can be added to deal with areas where vertical tabs aready exist. This will mean that popups will have access to vertical tabs natively, which is cool because it means we'll be able to use those for stuff like personal notes in the future.

**Comment by creesch** [comment]
Most of it makes sense except the last bit 

> Additionally, currently there are more or less two types of draggable window: absolutely positioned (move with page scroll, e.g. usernotes) and fixed positioned (don't move on scroll, e.g. personal notes). We should eliminate one or the other for a more consistent user experience,

Usernotes, historybutton, etc are related to a place on the page where they were opened. You might move them around to get a better... vantage point I guess? But in general I don't want to keep those to scroll with me when I am doing stuff. 

Personal notes are actually tied to more general stuff and I want those in reach no matter where I am on the page.

**Comment by Geo1088** [comment]
In my experience, the difference hasn't mattered much. In my experience at least, I pretty much never scroll away from a window with the intent to come back to it later; more often I just forget they're there when moving on through the feed. When I do scroll on, it's because I want to see something else on the page before I take an action in that window, and having to scroll back up to the window later could be obviated by just keeping the window with me as I scroll.

In general, if a window is open, I want access to it, and if I no longer need access to it, it's better to close it than just scroll past it. Anchoring all windows on the viewport rather than the document means that it's easier to tell what's open.

Ultimately though, I think this may just come down to preference. The spirit of this proposal is to cut down on complexity, and having two different types of position anchors does have complexity associated with it that I'd rather avoid.

**Comment by creesch** [comment]
I honestly don't think that it is too much complexity at this point and to me the distinction is rather clear and also how I use toolbox. 
Again, I do like the rest of your proposal and do fully agree there.

**Comment by Geo1088** [comment]
One other thing that I just realized we'll have to do as part of this: Popups currently default to horizontal tabs, while windows default to vertical ones. Since no popup has vertical tabs and there's a mix of overlays with horizontal and vertical tabs, I think it would make sense to have the refactored default tab arrangement to be horizontal, and add a modifier for vertical tabs for use in the sub config overlay, etc.
