### ISSUE TITLE
Removed comment cause error in context-popup

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#252]
Clicking `context-popup` on a comment that has been removed, it will not give any feedback and this error is outputted

![image](https://user-images.githubusercontent.com/6598829/76160404-6e94fd00-612a-11ea-9557-58aabea49f2a.png)

**Comment by creesch** [comment]
Removed in what sense? If you are a mod the removed status has no relevance here. 

![image](https://user-images.githubusercontent.com/2502190/76160904-5f17b300-612e-11ea-9aed-9122120c4c8d.png)

**Comment by SpyTec** [comment]
On a user's profile for a comment on a sub I don't moderate

**Comment by creesch** [comment]
Hrm, also a bit out of scope for **moderator** toolbox ;) But we probably should handle it gracefully. I am going to wait until @Geo1088 is done with the fetch conversion though.
