### ISSUE TITLE
"Sort by items" button in /r/mod/about/modqueue subreddits list doesn't show up for non-English display languages

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#293]
whew that's a mouthful

https://www.reddit.com/r/toolbox/comments/fv4rba/having_trouble_finding_the_option_to_sort/fmgfjem/

**Comment by Blank-Cheque** [comment]
A deceptively simple issue. The position to place the button is found by searching for the text "THESE SUBREDDITS" and there's no other hint to where the element is given by reddit e.g. class, id, even all the preceding elements are non-unique.

**Comment by Geo1088** [comment]
Might be able to make use of jQuery's `:has` selector extension to get around this, I'll investigate
