### ISSUE TITLE
Using post flair IDs alongside CSS classes and text

### ISSUE THREAD

**Issue by Xeoth** [toolbox-team/reddit-moderator-toolbox#296]
Currently, while using a removal reason, the only two options regarding flairs are to assign flair text and class. New Reddit introduced flair IDs.

Could toolbox assign flairs based on their IDs when applying a removal reason?

**Comment by Geo1088** [comment]
Seems like a good request, I'm assuming we'd have to implement the flair ID selector as a dropdown with the current sub's available flair templates as options.

Do you know whether or not the text and CSS class can be changed while maintaining the template ID? Or is the template ID changed/removed if the text or CSS class is updated? If the latter is true, we'll also want to disable the text/class fields if a template ID is selected.

**Comment by Xeoth** [comment]
I like the dropdown idea.

Text and Class can absolutely be changed while maintaining the ID, so no need for disabling anything :)

**Comment by Geo1088** [comment]
Cool, we can just autofill the other two fields when the dropdown changes without much hassle then. We'll probably have to start caching flair information with the other subreddit settings we keep track of, but this feature shouldn't be too difficult to implement.

**Comment by creesch** [comment]
>  ID selector as a dropdown with the current sub's available flair templates as options.

That's way fancier than what we have now for flair classes :P

**Comment by Geo1088** [comment]
To be fair, it's much easier to remember a CSS class than a machine-generated ID :P

**Comment by creesch** [comment]
I don't know what made me think of this issue but today I also realized that we probably want to add ID support to the modbutton flair methingy for users.

**Comment by Xeoth** [comment]
It'd probably have to be a dropdown since there's no way to memorize those long, meaningless strings.
