### ISSUE TITLE
Fix the "show settings" button

### ISSUE THREAD

**Issue by Xeoth** [toolbox-team/reddit-moderator-toolbox#298]
There are a couple issues with that. First and foremost, it's completely useless for now. It displays an empty text box no matter what settings you have. Secondly, it cannot be closed with the "X" button. The only way to do that is to reload the page. Lastly, the window appears behind the settings, so you have to close them first to access the popup at all (see screenshot).

![the box appears behind](http://i.imgur.com/d8AkRWZ.png)

Bonus points for implementing importing settings without having to make a private subreddit ;)

**Comment by creesch** [comment]
> Bonus points for implementing importing settings without having to make a private subreddit ;)

that would be outside the scope of this issue though. The settings here are a bit anonymized so they can semi safely be shared.

I think that once we have implemented storage using the webextension synced settings method it also isn't needed anymore.

**Comment by Geo1088** [comment]
(#226 is the relevant issue for settings sync via `browser.storage.sync`)
