### ISSUE TITLE
Auto-archive fails with wrong reason

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#306]
I was trying out auto-archive and it said "error, failed to send modmail" rather than failed to lock. Toolbox sent the modmail but didn't archive it.

Need to look more into

1. the error message, and
1. handling of archive fail message to avoid multiple removals.

**Comment by Geo1088** [comment]
FWIW I've been using the "archive thread" action on modmail macros for a while and it works like a charm. Probably some difference between the two implementations, though I haven't been looking at the code for a while.

**Comment by creesch** [comment]
Oh yeah that is totally different, for macros I basically said `"fuck it, we'll just click the buttons"` as I didn't want to confuse people with the actions not being visible. So for macros no API is touched.

**Comment by Geo1088** [comment]
Hmm, it seems like this is already being handled correctly. https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/removalreasons.js#L894-L914

Could it be that the reply call returned an error code, but the server processed the message anyway? I can't identify any logical errors in our promise handling here.

**Comment by SpyTec** [comment]
I will look into it when I can. Even if it's Reddit's fault we should handle it correctly so people don't send multiple Modmails

**Comment by SpyTec** [comment]
Fixed in dfb9790
