### ISSUE TITLE
Idea: Support HTML checkboxes inside of removal reasons

### ISSUE THREAD

**Issue by OldGoldie** [toolbox-team/reddit-moderator-toolbox#307]
We have a low-effort post rule that covers multiple things, and currently use a dropdown to specify which part of the rule they violated, but sometimes it may be multiple. So similar to the dropdowns, I was thinking it'd be nice to be able to use checkboxes in the preset removal reasons. Here's a little mockup I made:

![image](https://user-images.githubusercontent.com/20398111/80768151-351bb500-8b0f-11ea-80ee-c241d85a3657.png)

**Comment by creesch** [comment]
Seems like this is effectively the same as #156 in what it is trying to accomplish so I am closing this issue as a duplicate. Good suggestion nevertheless.
