### ISSUE TITLE
Mod button fails silently if mod does not have access permissions

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#309]
When mod actions is opened through mod button, it will try to access the banned users list. If the mod does not have `access` permission this will fail and we do not catch the error.

https://github.com/toolbox-team/reddit-moderator-toolbox/blob/d5f9ec2/extension/data/modules/modbutton.js#L334

This probably has two effects:

1. Mods can't go to user flairs to do flair actions
1. Mods can't close the mod actions window as no event listener is added

We should ideally catch this and disable or remove the ban tab altogether if the mod does not have access permissions.

**Comment by Geo1088** [comment]
Do you remember what permissions people did have when this issue came up? I'm trying to reproduce this, but API calls aren't returning a subreddit name if I don't have `access` permission which means I don't see anything but the flair tab. This might be an entirely separate sort of bug, not sure.

**Comment by SpyTec** [comment]
From Discord, here's the error we got from Decketio

![image](https://cdn.discordapp.com/attachments/535490561478492161/707171782028820480/unknown.png)

**Comment by Geo1088** [comment]
I think I reproduced, thanks. Will try to work on today.
