### ISSUE TITLE
Nuke button doesn't show up in modqueue

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#314]
Don't remember if this was an intentional omission to prevent abuse, but been doing a lot of spoiler removals on /r/anime recently and being able to nuke all the responses to a comment without having to open the context popup would be very helpful.

**Comment by creesch** [comment]
> Don't remember if this was an intentional omission to prevent abuse

I suppose a bit of both. It probably should show up in the context popup but not on single comments in the queue as then people would be nuking stuff without looking at the surrounding context.

**Comment by Geo1088** [comment]
w/e, closing as intended behavior

**Comment by Geo1088** [comment]
never actually closed this?
