### ISSUE TITLE
Add icon for user notes to "moderated subreddits"

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#316]
It's a little confusing that the only place to access the full user notes page is under the other :arrow_forward: menu which I normally consider to be the "user profile menu". It seems like it should just be next to all of the other subreddit-specific stuff in the "moderated subreddits" menu.

Thanks.

**Comment by creesch** [comment]
That's because all toolbox features are consolidated there for both new and old reddit to give it one place. On new reddit we couldn't add it anywhere else anyway.

**Comment by Geo1088** [comment]
Seems like a good idea to add it there as well, working on it now.
