### ISSUE TITLE
Toolbox buttons aren't readable in RPAN chats

### ISSUE THREAD

**Issue by ParadoxMajor** [toolbox-team/reddit-moderator-toolbox#321]
![image](https://user-images.githubusercontent.com/57575452/82766470-6c6b4200-9ded-11ea-9557-fa088fde2741.png)

I used Stylus to fix the styling with this code, but it'd be nice if mods didn't have to override it that way.

`body.mod-toolbox-rd .tb-general-button, body.mod-toolbox-rd li a.tb-general-button, body.mod-toolbox-rd .tb-bracket-button {
    background-color: transparent !important;
    color: rgba(255,255,255,.8) !important;
    border-left-width: 1px !important;
}`

If you need an RPAN sub to test on, let me know!

**Comment by Geo1088** [comment]
Hmm... We should probably just reconsider having the button background be transparent. There's not really a good way to dynamically set text color based on the background the button is on, and I'd rather not hardcode an exception for this specific area.

**Comment by ParadoxMajor** [comment]
But whatever color you choose will be a problem in regular non-night mode vs. the night mode of RPAN chats (which is independent of your night mode setting)

**Comment by Geo1088** [comment]
I think it'd be fine for the buttons to just always have a dark-text-on-light-background color scheme. It won't be the prettiest for dark themed areas, but we don't have any good way of knowing if our buttons are being put on light or dark areas of the page, so the best we can do is pick one thing that will at least be readable everywhere, even if it's not the prettiest.

**Comment by adhesivecheese** [comment]
Given that RPAN was [discontinued over a year ago](https://www.reddit.com/r/pan/comments/yl5zzd/update_on_the_future_of_live_video_broadcasting/), this is probably a closeable issue, as button transparency wasn't ever an issue anywhere else.
