### ISSUE TITLE
Add "source" button to new modmail

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#323]
Please add a `source` button to each modmail to view the Markdown source of the message.

Thanks!

P.S. I realize the `source` button that we all know and love is a RES feature, but [it doesn't look like RES is going to be supporting this feature on the redesign in general any time soon](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/4951), let alone new modmail. And while I can almost entirely avoid the redesign as a moderator, I cannot avoid new modmail.

**Comment by creesch** [comment]
Not a bad idea in theory, bit annoying to get working in practice due to how new modmail works. I'll think about a way to implement it though.
