### ISSUE TITLE
Mod bar appears on Crisis Text Line popup

### ISSUE THREAD

**Issue by ParadoxMajor** [toolbox-team/reddit-moderator-toolbox#324]
Via the report dialog when you select "user is considering suicide or self harm."  Workaround is to hide it.

![Screen_Shot_2020-04-23_at_9 12 29_PM](https://user-images.githubusercontent.com/57575452/83992126-31086180-a91d-11ea-9e1f-1f4125d83139.png)

**Comment by Geo1088** [comment]
Related to #71. Knew I was missing something when I closed that.
