### ISSUE TITLE
Delisting personal notes returns with an error even though the action seems to work.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#326]
As the title says. 

Clicking the little garbage bin results in that error. 

Creating and saving personal notes works fine.

**Comment by Geo1088** [comment]
could be more shenanigans from `fetch` conversion, I'll take this one

**Comment by creesch** [comment]
@Geo1088 I seem to remember you fixing this at some point? I can't reproduce so it seems like so.

**Comment by Geo1088** [comment]
I haven't submitted a fix for this. IIRC was waiting to see what you or spytec thought the best strategy for it would be.

**Comment by creesch** [comment]
Oh... I just realized I am running the latest stable release due to my fixes. Lemme switch to that. 

As far as my thoughts are, to be frank, what is easiest to implement (without a mess) so we can get it to work. 

A seperate method is probably the cleanest way to handle this considering that the alternative is building in a check in the current method for wiki stuff and in that case handle things differently. At that point you effectively have two methods mixing anyway.

**Comment by Geo1088** [comment]
Sounds good. Will PR today after work.
