### ISSUE TITLE
The mod buttons sometimes multiply in number

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#330]
By "mod buttons", I mean `[N] [M] [H]` etc. next to usernames in threads. I am using Chrome 84, Toolbox 5.3.1, and RES 5.18.14.

This seemed to happen after several edits of each of my comments in this thread (my parent comment higher in the thread did *not* have this happen). 

[This image showing the issue](https://imgur.com/a/iCV4hfa) should be fairly self-explanatory.

Thanks.

**Comment by Geo1088** [comment]
When a comment is edited, the mod buttons are removed from that comment and regenerated, but regenerating the buttons also causes the buttons to be re-added on all child comments even though they were never removed. Not sure what the specific interaction is (do we remove the buttons or does Reddit?) but should be possible to work around.

**Comment by Geo1088** [comment]
This can probably be fixed with a change to the oldreddit module pretty easily, actually.
