### ISSUE TITLE
RR triggered when removing comment in context-popup with comment RR disabled for both toolbox and subreddit. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#334]
The same comment didn't trigger RR when removed in the regular context.

**Comment by creesch** [comment]
I am guessing that the last PR that did  enable RR in context popup did overlook some logic needed to make it work properly, specifically: 
https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/removalreasons.js#L194-L201

Which is a problematic bit as well as it has a check on old reddit
where the context popup and other contexts where it was enabled can show on both reddits.

**Comment by Geo1088** [comment]
isComment = $thing.hasClass('comment') || $thing.hasClass('was-comment');

should be changed to include `|| $thing.hasClass('tb-comment')`. Didn't notice that bit before. Should be all that's needed, will PR later.
