### ISSUE TITLE
Possibly rework TBNewPage to not need so many regex

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#344]
After thinking it over a bit it might be easier to just break down the path into an array and work from there. 

Something along the lines of if the first key is an `r` it is a subreddit and continue checking in there and the same for other pages. 

@Geo1088 I know you wanted at some point look into this, what do you think?

**Comment by Geo1088** [comment]
Related to #70, maybe duplicate? Can't tell if we're talking about the same section of code or not. This is definitely a good idea though.

**Comment by creesch** [comment]
Oh yeah dupe for sure, I couldn't find that one though I did remember us talking about it. I'll close this one in favor of #70.
