### ISSUE TITLE
Incorrect core sorting in queue tools

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#372]
http://prntscr.com/ufs7bb

https://discordapp.com/channels/535490452066009090/535490561478492161/754081204508164330

**Comment by creesch** [comment]
https://github.com/toolbox-team/reddit-moderator-toolbox/blob/05a0e4d920fd50b9cb8d4da25b46ba180e631709/extension/data/modules/queuetools.js#L913-L991

**Comment by Geo1088** [comment]
gotta love it when the bug lives in a function with the comment "this function is evil"

**Comment by Geo1088** [comment]
Found the issue, should be looking at the score element's `title` attribute (which has the actual score as a number) instead of its text (which uses `k` for large scores). Will PR shortly.
