### ISSUE TITLE
sort out css

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#384]
We already started organizing them per module but there is a lot of unused CSS and almost none of it has proper commenting.

**Comment by TheAlpacalypse** [comment]
Is this something I can help with? I feel like this wouldn't be something too technical

**Comment by creesch** [comment]
Well it involves sorting out what css is still in use, where it is used, etc and properly commenting it etc.

**Comment by TheAlpacalypse** [comment]
Yah AgentLame told me I should probably not touch that in case I deleted something important

**Comment by agentlame** [comment]
>AgentLame

All lower case; no spaces. >:(

**Comment by TheAlpacalypse** [comment]
> All lower case; no spaces. >:(
q.q yes senpai

**Comment by TheEnigmaBlade** [comment]
H E ' S A G E N T L A M E B O Y S

**Comment by agentlame** [comment]
#WHAT DOES THIS ISSUE EVEN MEAN?!?!?

**Comment by creesch** [comment]
CSS is badly commented,  some parts are no longer in use,  etc.

**Comment by creesch** [comment]
closing this as this is already being done in v4 in the other repo.
