### ISSUE TITLE
cleanup: Replace jQuery array utilities ($.each, $.inArray) with ES6 equivalents

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#39]
Since we're assuming ES6 now, we can make this easier on ourselves:

- `$.each(arr, (i, val) => {})` becomes `arr.each((val, i) => {})`
- `$.inArray(thing, arr) !== -1` becomes `arr.includes(thing)`
- `$.inArray(thing, arr)` becomes `arr.indexOf(thing)`

**Comment by creesch** [comment]
Okay we need to put in some effort of actually doing this otherwise this isn't going to happen. 

One thing though

> * `$.inArray(thing, arr) !== -1` becomes `arr.includes(thing)`
> 
> * `$.inArray(thing, arr)` becomes `arr.indexOf(thing)`

I am fairly sure most if not all there can be replaced with `arr.includes(thing)` or  `!arr.includes(thing)` unless I am missing something.

**Comment by Geo1088** [comment]
Yeah I'm pretty sure that's the most common case. I think there might be a couple cases where we're re-ordering stuff in arrays where we do use `$.inArray` to get an actual index rather than just whether or not an element exists though.

Either way I expect it won't take long to get this done, I can do a quick run-through of some of this in a bit.
