### ISSUE TITLE
Update codemirror to latest version.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#396]
It has been a while since we updated it (18 months)

**Comment by creesch** [comment]
Updating this issue as we are now using rollup and we should explore using codemirror in the same way 

https://codemirror.net/examples/bundle/

**Comment by eritbh** [comment]
Dependabot has been configured to give us 5.x updates for a while now, and we have a separate issue for upgrading to v6 #635. Closing this one in favor of that
