### ISSUE TITLE
Mod Button and Usernotes are unclickable on /about/banned

### ISSUE THREAD

**Issue by Xeoth** [toolbox-team/reddit-moderator-toolbox#420]
You cannot access the Mod Button and Usernotes from the user hovercard in the ban list (https://reddit.com/r/subreddit/about/banned) on new Reddit.

There are no errors or unexpected log messages in the console, and the issue is reproducible both on Firefox and Chrome.

**Comment by Geo1088** [comment]
Can't reproduce on 5.4.3 in FF 83 (tried with /r/toolbox). Needs investigation.

**Comment by creesch** [comment]
I assume on new reddit and I am guessing that it has to do with jsAPI sending a slightly different context toolbox isn't setup to handle properly.

**Comment by Geo1088** [comment]
Issue explicitly says new Reddit, that's what I was testing on and couldn't observe any difference in available buttons. I tried both loading the page directly and navigating there from the "mod tools" menu, thinking that the sent info might be different depending on how the page was loaded, but no dice.

**Comment by creesch** [comment]
I figured it was that the buttons aren't working, not that they aren't available.

**Comment by Geo1088** [comment]
Oh, derp. You're right, reproduced.
