### ISSUE TITLE
purifyObject gets called on a string if wiki read fails

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#423]
[call is in macros, line 34](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/macros.js#L34)

Looks like earlier checks are calling a callback function but not returning early, potentially resulting in the callback being fired multiple times. This is bad. Should look for similar situations elsewhere.

**Comment by creesch** [comment]
Oh I forgot I saw that, the entire function there needs to be looked at as it shouldn't even reach that point but because we fail to return [here](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/modules/macros.js#L26) it does...

**Comment by creesch** [comment]
I need ☕, you basically said the same thing as me. But yeah, shit is broken there.
