### ISSUE TITLE
Context-popup does not appear if the user deleted their account

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#429]
Reported on discord

![image](https://user-images.githubusercontent.com/2502190/101983285-6732ef00-3c7a-11eb-9510-cc40d58468c9.png)

**Comment by Geo1088** [comment]
Related to #252, might be already fixed for 5.5?

**Comment by creesch** [comment]
Oh in that case it is probably fixed, I didn't try it yet mainly made the issue so I wouldn't forget.

**Comment by Geo1088** [comment]
Separate issue, reproduced on latest master. Working on a fix for 5.5.
