### ISSUE TITLE
fix issue with it not working under some conditions

### ISSUE THREAD

**Issue by agentlame** [toolbox-team/reddit-moderator-toolbox#429]
This is a place holder.  It needs some testing (@psdtwk, maybe you can help on this?) to see all the circumstances in which it doesn't work at all, or doesn't work as expected.

We had some issues pointed out during the 3.0 beta, but we pushed/ignored them for the release. 

Just add comments to this issue with all the found problems and we'll knock them out as they come up.  We can file new issues and defer them to another release as needed.

**Comment by psdtwk** [comment]
lol sorry about that. I thought it'd let me assign two people.

**Comment by agentlame** [comment]
Nah, that's actually fine the other way.  I was going to assign it to you but didn't want to be a dick.

**Comment by creesch** [comment]
I just want to say that I love the title of this issue.

**Comment by agentlame** [comment]
If there's one thing we all know to be true, it's that: specificity is my defining characteristic.

**Comment by Dakta** [comment]
Can we get some confirmation or increased specificity on this issue? Tag it "confirmed" when it can be reliably reproduced.

**Comment by agentlame** [comment]
>Can we get some confirmation or increased specificity on this issue? 

What's to confirm?  It just doesn't work sometimes.  The point of this issue is to find which circumstances under which it does not work.

**Comment by Dakta** [comment]
K, I guess I hadn't noticed it not working.

**Comment by agentlame** [comment]
Leaving this module in beta.  We'll fix it up in 3.2+

**Comment by agentlame** [comment]
Aaaaand... leaving this in beta for another release.
