### ISSUE TITLE
Truncate message field when sending modmail

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#432]
[Context](https://old.reddit.com/r/toolbox/comments/k90nqg/error_failed_to_send_modmail_as_a_removal_reason/gftpbua/?context=3) at least in removal reasons, can't hurt to check a few other places as well. 

Possibly also want to do so for the message body itself.

**Comment by Geo1088** [comment]
Possibly related to #376? Not sure what happened with that one anymore.

**Comment by creesch** [comment]
Seems like it, though in a different area. I am not sure we truncate subject lines or messages from removal reasons. 

We might want to solve this at the TbApi level for sending modmail.

**Comment by Geo1088** [comment]
I can't reproduce this with a custom `pmsubject` as described in the Reddit thread. `TBApi.sendMessage`'s `subject` field seems like it's already truncated to 99 characters: https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbapi.js#L615

The `message` field isn't truncated, should have a max length of 10000. I'm guessing that's the actual cause of the issue.
