### ISSUE TITLE
Change webext API calls to use browser instead of chrome

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#44]
Firefox implements a promise-based version of Chrome's `chrome.*` extension API, referenced as `browser.*`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API

It also provides a polyfill to support Chrome: https://github.com/mozilla/webextension-polyfill

Given we're converting lots of our code to promises, I think it would make sense to use a promise-based browser API since it doesn't seem like it's otherwise much different (shouldn't require much logic rewriting, just cleanup).

**Comment by creesch** [comment]
Yeah the problem with that used to be edge, with edge switching to chromium that hopefully shouldn't be an issue anymore.
