### ISSUE TITLE
Convert $.ajax calls to use fetch

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#45]
Related to #44 

[`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is supported on all relevant browser versions and has a much nicer API than `$.ajax` does. 

Because `$.ajax` passes three parameters to its callbacks, it's more difficult to have it play well with promises, which can only represent a single value (we get around this now by promising an object with the callback values as properties, but this isn't ideal). `fetch`, on the other hand, promises a single [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) object.

Additionally, `Response` is (relatively) easily serializable to/from JSON - e.g. we can get the response from the background page, convert it to JSON, and then let `TBUtils.sendRequest` convert the JSON it received from the background page back into a `Response` object with its [constructor](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response). For example:

```js
// background script
browser.runtime.onMessage.addListener(async request => {
    const response = await fetch('...');
    const headers = {};
    for (const [k, v] of response.headers) {
        headers[k] = v;
    }
    return [response.text(), {
        status: response.status,
        statusText: response.statusText,
        headers,
    }];
});
// content script
const response = await browser.runtime.sendMessage({...}).then(responseData => new Response(...responseData));
doSomethingWith(response.json());
```

**Comment by creesch** [comment]
Just as a headsup, fetch seems simpler but also needs more scaffolding to make it actually work properly in regards to error handling. [See this](https://gomakethings.com/why-i-still-use-xhr-instead-of-the-fetch-api/). 

I also remember reading it doesn't work as nicely with cookies and sessisons as xhr does. 


Anyway, if we can replace the jquery ajax calls with it then it is absolutely fine.

Alternatively we could use [axios](https://github.com/axios/axios) which is promise based and a solid framework.

**Comment by Geo1088** [comment]
That article seems to make things a bit more complicated than it has to in regards to error handling. Since all our requests are happening from one bit of code, it's easy enough to add `.then(response => response.ok ? response : Promise.reject(response))` to the helper, and then we can catch non-OK responses along with incomplete requests just like normal.

Cookie support seems easy enough too, we just need to add the `credentials` parameter, which again, since we're using helper functions for all our requests, can easily be added for all requests. https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters

All good things to keep in mind when we implement it though. This change will definitely need a fair amount of testing before it's good to go.

**Comment by creesch** [comment]
Stickied this one as we are currently running into some issues it seems with ajax jquery, specifically redirects when reddit thinks you should log in. ajax can't pick up on them and then we get served an html pages. 

So it might be beneficial to explore this a bit further soonish. 

After recently having played around with fetch it seems indeed that the scaffolding surrounding it is doable. 


For example this is what I did in another project.

```javascript 
function handleWiki ({method, body, slug}) {
    return new Promise((resolve, reject) => {
        // If we don't have a method we can't continue
        if (!method) {
            reject('no method defined');
        }

        // Set up the initial request params.
        const requestInit = {
            method,
            headers: {
                'PRIVATE-TOKEN': privateToken,
            },
        };

        // Add a body if we need to.
        if (body && method !== 'GET' && method !== 'HEAD') {
            requestInit['body'] = JSON.stringify(body);
            requestInit.headers['Content-type'] = 'application/json';
        } else if (body) {
            reject(`body not allowed with ${method}`);
        }

        let requestURL = `https://gitlab.com/api/v4/projects/${projectID}/wikis`;
        if (slug) {
            requestURL = `${requestURL}/${encodeURIComponent(slug)}`;
        }

        const apiRequest = new Request(requestURL, requestInit);

        fetch(apiRequest)
            .then(response => {
                if (response.ok) {
                    return response;
                }
                return reject({
                    status: response.status,
                    statusText: response.statusText,

                });
            })
            .then(response => response.json())
            .then(response => {
                resolve(response);
            });
    });
}
```

Called through 

```javascript
    handleWiki({
        method: 'GET',
    })
        .then(response => {
            // do stuff with response
        }).catch(error => {
            console.error(error);
        });
```

Which as you pointed already out can likely be simplified :P Just pasting it in here as reference.

**Comment by creesch** [comment]
Oh what I wanted to actually type is that we need to make sure we can handle redirects with fetch properly 😁

**Comment by Geo1088** [comment]
I'm gonna look into implementing this soonish. Do we generally want to disallow redirects or follow them?

**Comment by creesch** [comment]
Error on redirect I believe.

**Comment by creesch** [comment]
As I got reminded by the other jquery related issue we tackled the other day, any progress here? There is no rush as using jquery for now is fine.

**Comment by Geo1088** [comment]
Still on my radar for when I'm done with (or get bored of) #245
