### ISSUE TITLE
Flair selection has visual bugs with flair template selection

### ISSUE THREAD

**Issue by SpyTec** [toolbox-team/reddit-moderator-toolbox#457]
Introduced in #418. There are both bugs and edge-cases not taken care of:

- [Clearing a flair doesn't work?](https://www.reddit.com/r/toolbox/comments/lqhs25/bugs_unable_to_save_blank_css_flair_class_and/)
- No way to get value from flair templates to text and class
- It is not clear if selecting a flair template will overwrite text and class

**Comment by Xeoth** [comment]
> Clearing a flair doesn't work?

Cannot reproduce that

> No way to get value from flair templates to text and class

Do you mean that changing the flair template should override the fields right after selection? Right now, class and text are filled silently after clicking Save if not typed in by the user.

**Comment by ickybus** [comment]
>Do you mean that changing the flair template should override the fields right after selection? Right now, class and text are filled silently after clicking Save if not typed in by the user.

this is not the behavior experienced when selecting template "None" - i had to both select "None" *and* manually clear the field to get it to save.

**Comment by Xeoth** [comment]
Ah, in that way. Can reproduce now. It seems like Reddit's API autofills the template ID when the user has one already, but is not specified in the request. Will dig into how to avoid that.
