### ISSUE TITLE
Context Popup does not work on user profile threads

### ISSUE THREAD

**Issue by OldGoldie** [toolbox-team/reddit-moderator-toolbox#463]
For a simple example, see the profile https://www.reddit.com/user/ModTips

The context-popup button does not work on threads in u/ModTips. Purely an example, I've ran into this before on other profiles, so it's not just this one.

**Comment by creesch** [comment]
Can confirm the behavior, it appears that somehow with this profile we aren't picking up the post ID for these comments resulting in jsAPI info missing. 

The post ID should come from `TBCore.getThingInfo` so there probably is something funky going on with the html for these comments.

**Comment by creesch** [comment]
I think I have found the issue, it is this line https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbcore.js#L814 as the regex there expects /r/ notation for permalinks not the profile notation.

**Comment by eritbh** [comment]
Believe this was fixed by #505, working now in 5.6.3
