### ISSUE TITLE
Toolbox causes errors when replying to certain modmails when either `checkfornewmessages` or `lastreplytypecheck` is enabled. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#470]
https://www.reddit.com/#?tbsettings=newmodmail&setting=checkfornewmessages
https://www.reddit.com/#?tbsettings=newmodmail&setting=lastreplytypecheck

This appears mostly to happen with older modmails for some reason. So reproduction steps: 

1. Find an old modmail, I used a random new modmail onboarding message send by reddit. 
2. Have one of the above settings enabled. 
3. Try to reply to the modmail

Expected: 

- You get to reply with no issue 

Actual: 

- A red `undefined` error briefly shows then the page reloads to the listing view.

**Comment by creesch** [comment]
The above is true for firefox, I just tested in Edge and there I can't reproduce this. So I am fairly sure this is related to the same thing @molenzwiebel fixed (or attempted to anyway) as that was also firefox related.

**Comment by umbrae** [comment]
Just wanted to say thanks for the amazingly fast turnaround on this @creesch @Geo1088!

**Comment by Geo1088** [comment]
No worries, thanks for bringing it to our attention :)

**Comment by umbrae** [comment]
Just wanted to say that I verified this as fixed in the most recent version for FF, thanks again!

**Comment by creesch** [comment]
Good to hear and you are very much welcome :)
