### ISSUE TITLE
Toolbox Settings schema is missing values

### ISSUE THREAD

**Issue by adhesivecheese** [toolbox-team/reddit-moderator-toolbox#489]
As I mentioned [on Reddit earlier today](https://www.reddit.com/r/redditdev/comments/muk0bc/introducing_a_very_much_still_alpha_python/gvgvalm/), the settings schema page is missing some of the newer values. If there's a way to submit a pull request for a wiki page, I'm too dense to find it, but I've gone through and added all the missing values I saw and filled in as many TODO's as I was sure of, so if somebody with appropriate permissions wants to grab the updates and toss them into the wiki, please do. You can find the updated markdown here: https://pastebin.com/raw/RMRnJufJ

**Comment by creesch** [comment]
Thanks! Yeah there doesn't seem to be a good way to do that for wikis except for opening them up completely. I'll have a look later today and update the wiki.

**Comment by creesch** [comment]
Updated, thanks again!
