### ISSUE TITLE
In-page notifications never get displayed

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#51]
Now that notifications are displayed from the background page, we always have permission to display them and therefore the in-page ones are completely unused. We should probably move that to a setting for people that prefer the in-page ones to the native ones, or otherwise remove the code for them.

**Comment by creesch** [comment]
>  or otherwise remove the code for them.

I am leaning towards this. But leave the code in for now and see how many people complain when we release it eventually so we can potentially make it an option.

**Comment by Geo1088** [comment]
One person on my team already complained about it, we'll see if it's a common sentiment or not. I'm okay with it either way, though it is a fair amount of code we'd have to maintain for making sure the notifications appear on all relevant pages, etc.

**Comment by Geo1088** [comment]
closing in favor of #99
