### ISSUE TITLE
Usernote manager, sort by note type.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#550]
"Requeste" here: https://www.reddit.com/r/toolbox/comments/soiyfs/not_allowing_us_to_sort_usernotes_by_the_type/

Additionally, colors aren't shown in the usernote manager. We might as well add those.

**Comment by dequeues** [comment]
I'll take a look at this in the next few days

**Comment by creesch** [comment]
I think this might already be implemented recently.

**Comment by creesch** [comment]
Ah I was thinking of the filtering PR you did a while ago. https://github.com/toolbox-team/reddit-moderator-toolbox/pull/546 

I think that that PR actually does cover the use case for this issue as well. Although if you also want to add sorting in addition to filtering then that is absolutely fine :)

**Comment by dequeues** [comment]
You're right, it pretty much does cover it. I could add the colors to the usernote though?

**Comment by creesch** [comment]
Sure! :)

**Comment by eritbh** [comment]
Closed in #560
