### ISSUE TITLE
Update toolbox to accept 5000 character ban notes. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#562]
https://www.reddit.com/r/modnews/comments/tt5rjw/april_mod_experience_product_update/

> The previous ban message had a 1,000 character limit. We heard from several of you that having a higher character limit would allow you to better communicate ban reasons with users and potentially reduce some of the back and forth that occurs. Based on those conversations we went ahead and increased the ban notes character limit to 5,000.

**Comment by eritbh** [comment]
Closed in #563
