### ISSUE TITLE
UI improvement options for new Modmail sidebar

### ISSUE THREAD

**Issue by eritbh** [toolbox-team/reddit-moderator-toolbox#581]
As requested around here: https://discord.com/channels/535490452066009090/535490561478492161/1009524587203153991

The new design for the modmail sidebar dedicates way too much space to the user's snoovatar and not enough to the scrollable elements which contain the user's mod notes and conversation history. We could include an option to remove or downsize the snoo and make more space for useful information. I proofed this out with a user style: https://eritbh.me/userstyles/#compact-modmail-user-info

Additionally, the only link to the user's profile page is in the small "view profile" link. We could make the username, display name, or snoo image clickable links to the profile as well.

**Comment by creesch** [comment]
The change was rolled back for now: https://www.reddit.com/r/ModSupport/comments/wqw3x9/please_roll_back_the_modmail_update/ikpv267/

Hopefully they already tone down the avatar, as for the rest we just need to wait what their next move will be.
