### ISSUE TITLE
"Sticky" button on link listings

### ISSUE THREAD

**Issue by empyrical** [toolbox-team/reddit-moderator-toolbox#593]
Because of the new double sticky feature on reddit, I think something like this might become super useful.

[The reddit API](https://www.reddit.com/dev/api#POST_api_set_subreddit_sticky) for stickies has a feature to specify which slot you want the sticky to go in to, which this could take advantage of.

It could be a new link in the gutter of a listing, like this:

![](https://i.imgur.com/qr3sOHT.png)

And when you click it, you see this:

![](https://i.imgur.com/j8MWrSI.png)

And an "unstick" link on existing stickies, so you could unstick a sticky from the listing too.

**Comment by agentlame** [comment]
I like this.   Just with our release I had to shuffle around the stickies.

**Comment by Geo1088** [comment]
Been meaning to do something like this for a while actually, especially given BB already has an "unsticky" button on listings.

**Comment by Geo1088** [comment]
Closing in favor of https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/issues/69
