### ISSUE TITLE
Bottom bar and context menu open and close on every page load

### ISSUE THREAD

**Issue by dequeued0** [toolbox-team/reddit-moderator-toolbox#607]
The bottom bar and context menu now open up and close every single time a new Reddit page is loaded or reloaded.

Here are two screen recordings showing a page reloading with Chrome and Firefox, respectively:

https://imgur.com/a/2bLJbx9

The bottom bar opens about 5-6 seconds before the end of each video and the context menu opens about a second later. The context menu is usually open for a longer period of time, but I've seen the bottom bar open up for as long as a second too.

I found a previous page load video I created with Toolbox 5.4 and you can't see this happening at all:

https://imgur.com/bcpj0Pt

**Comment by eritbh** [comment]
This could be related to asynchronous loading of module settings in 6.0 - will investigate and see if I can reproduce

**Comment by eritbh** [comment]
Found the issue that was causing the modbar to present expanded initially; will put out a fix.

The context menu opening when new items are added (i.e. on page load) is controlled by a setting: "General settings" > "Select what effect the context menu uses to show that new items are available" - does it continue to pop up on page load if you change that setting to "none"?

**Comment by dequeued0** [comment]
> The context menu opening when new items are added (i.e. on page load) is controlled by a setting: "General settings" > "Select what effect the context menu uses to show that new items are available" - does it continue to pop up on page load if you change that setting to "none"?

No. It does not pop open on page load after changing that setting. Thanks and thanks for the bug fix for the modbar.
