### ISSUE TITLE
Make all four columns fit on the same line if there is enough room

### ISSUE THREAD

**Issue by agentlame** [toolbox-team/reddit-moderator-toolbox#693]
![image](https://cloud.githubusercontent.com/assets/1383602/11571658/72464376-99cb-11e5-99fd-71feea5b4f66.png)

**Comment by creesch** [comment]
Wouldn't it make more sense to limit it to two per "line"? 

Afaik that would make it a nice and easy to read and compare view. Something like this

![image](https://cloud.githubusercontent.com/assets/2502190/11571910/ff3fb18a-99fe-11e5-940a-af19c5cebe13.png)

**Comment by agentlame** [comment]
My only issue with that is when you have three open, it looks like my screenshot above.

**Comment by Geo1088** [comment]
Calling this good enough as the 2 and 2 layout has been adopted and there's no longer any scenario where only 3 of the 4 are displayed at once as of 79183d2.
