### ISSUE TITLE
Make mod buttons show up in consistent order

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#699]
We have had [some](https://discord.com/channels/535490452066009090/535490561478492161/1051597714049208340) reports that they now aren't in the same order anymore depending on where on reddit people are. I am guessing this has to do with us moving a lot of stuff to async operations, making modules not load in the same order every time. 

I am currently thinking that the easiest way to approach this is probably to just fix it in css with `order`.  That way we don't need any fancy logic.

**Comment by adhesivecheese** [comment]
This is an issue I've noticed for a while, though definitely noticed it much more frequently since the most recent update. The CSS order.

```
.tb-usernote-button { order: 1; }
.global-mod-button { order: 2; }
.user-history-button { order: 3; }
.tb-user-profile { order: 4; }
```

should fix it the right way (assuming I have the buttons in the right order; I'm struggling to remember the order of 2 & 3)

**Comment by eritbh** [comment]
Related to #91, in that we wanted to come up with a more general UI solution for grouping all our user buttons together at some point

**Comment by creesch** [comment]
Sort of, but this is more about the buttons previously always loading in order and no longer doing so. It also should be a relatively straightforward fix if we use flex order, just need to make sure it doesn't cause other weird things with text alignment and such.
