### ISSUE TITLE
Clear cache on user change. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#703]
Due to our improvements in caching some people are ironically running into a new issue. Specifically when switching accounts (mostly with RES) where toolbox still has the cache for the other account. 

In the past we tried to mitigate this somewhat by detecting clicks on the logout buttons and such. But that is a bit hacky and annoying to deal with. 

I have two ideas in mind on how to approach this. 

1. When requesting a cache item we send the username with it which we compare to the username the cache item was stored with. This should work for all cached things except for one important one https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbapi.js#L172 . Naturally when we can't fetch userdetails we can't send the username together with the cache request. 
2. Track it based on one of the cookies/session values reddit sets. I am not sure yet if there is one with a consistent value over old and new reddit tied to the logged in session ( `reddit_session` seems like it might be suited for the task), if there is I feel like this is the best way to approach this.

**Comment by eritbh** [comment]
Resolved in #745 I'm pretty sure
