### ISSUE TITLE
Modbar showing up in iframes

### ISSUE THREAD

**Issue by Geo1088** [toolbox-team/reddit-moderator-toolbox#71]
We need to make a list of pages that show up in iframes that we don't want to do toolbox things in. gg reddit.

- [x] Gilding popup
- [ ] Others probably

**Comment by creesch** [comment]
I think we already disable it in chat... (about 80% sure I had to deal with that). Once in a blue moon it shows up in ads, not much we can really do about the latter.

**Comment by Geo1088** [comment]
Gonna close this now, unless there are other known areas where it's still broken
