### ISSUE TITLE
Unable to create Mod Notes via "NN" button from Modmail

### ISSUE THREAD

**Issue by shiruken** [toolbox-team/reddit-moderator-toolbox#753]
Attempts to create Mod Notes via the "NN" button from the Modmail interface fail. Here's the error message appearing in the console:

![image](https://github.com/toolbox-team/reddit-moderator-toolbox/assets/867617/596c1acd-6096-44fa-a916-f1b28d3a637b)

It would be ideal if this were possible so that the permalink to the modmail message would be linked as context (this is not an option via the native Mod Notes interface).

**Comment by eritbh** [comment]
Oh, this is fun - Reddit doesn't actually support saving context when adding mod notes from modmail, so we can't either, but we're trying to send an ID anyway and it's causing Reddit to reject our requests. I don't know why I didn't think to test this before, thanks for the catch.
