### ISSUE TITLE
Sort comments in queue by thread

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#799]
Sometimes you have one of those days that one thread is causing a lot of issues, it occured to me it would be nice if we can sort all comments and such from that thread so they are together.

**Comment by creesch** [comment]
Or possibly not sorting but grouping by thread, leaving how it is sorted intact.

**Comment by Geo1088** [comment]
So this could basically take each comment, put them into groups, and then sort the groups by the newest comment in each group. That would mean the most recently active (report-wise, anyway) threads are on top.

I like the concept of sorting by thread a lot, actually.

**Comment by Geo1088** [comment]
Gonna start mocking this up locally if I find time this weekend.

**Comment by creesch** [comment]
Alright,  curious what you'll come up with. Don't commit it to master though, I really want to wrap up 3.6 soon

**Comment by Geo1088** [comment]
Forked the repo, I'll PR my branch when it's serviceable.

**Comment by Geo1088** [comment]
This was added with #806 and made to work with dynamic sorts in 4d9ef8bec0c4b9f4ad220a8c3057d8f2fe92b9a3, and given this repo is in maintenance mode I don't see a reason to keep it open further.
