### ISSUE TITLE
Give jsdocs a more structured place.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#80]
For toolbox v5.0 I moved to a single markdown page as that works best on the short term. In the long term I do want to automatically generate jsdocs to github pages that does not require manual action from us.

**Comment by Geo1088** [comment]
Best way to do this is probably using CI to generate on a `gh-pages` branch. Don't want the docs generation creating unnecessary commits on master.

**Comment by Geo1088** [comment]
Closing since https://github.com/toolbox-team/source-docs exists since a while ago.
