### ISSUE TITLE
Error loading user data on Toolbox User Profile

### ISSUE THREAD

**Issue by shiruken** [toolbox-team/reddit-moderator-toolbox#804]
The user profile overlay started having issues displaying user profile data:

![image](https://github.com/toolbox-team/reddit-moderator-toolbox/assets/867617/bba1ff32-6d17-431c-97d0-761529cfd096)

The following error message is generated in the console: `TypeError: date.toISOString is not a function at relativeTime`

![image](https://github.com/toolbox-team/reddit-moderator-toolbox/assets/867617/afd321a1-62b2-4b83-96b3-b83a29fbdcc6)

It appears [this call](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/da7379998b2925af57681b445868781a72c7c323/extension/data/modules/profile.js#L345) to `TBui.relativeTime()` is passing in the argument [as a string](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/da7379998b2925af57681b445868781a72c7c323/extension/data/modules/profile.js#L327) rather than [the expected Date object](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/da7379998b2925af57681b445868781a72c7c323/extension/data/tbui.js#L1870). Because this function is throwing an error, the entire sidebar of the profile fails to be generated.

**Comment by eritbh** [comment]
Done in #805, not sure why auto-close didn't work

**Comment by shiruken** [comment]
Ahh something isn't working right. Now the sidebar is rendering but the "joined on" date isn't actually showing.

I'm guessing [this](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/32b8beaed0c04d8c318287e3330ea0658eb6695f/extension/data/modules/profile.js#L345) selection needs the `.` before the class name?
