### ISSUE TITLE
replace/update spectrum colorpicker with one that doesn't use deprecated jquery functionality. 

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#841]
Spectrum uses `jQuery.fn.bind()`, `jQuery.fn.unbind()` and `jQuery.fn.delegate()` all three are deprecated in jquery.

**Comment by creesch** [comment]
Seems like we can use html5 colorpicker without much issue. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

I still need to double check with Edge if it works there as well.

**Comment by Geo1088** [comment]
Looks like [it's all good](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6514216--input-type-color)

**Comment by Geo1088** [comment]
Only instances of this seem to be in [core config](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/d23dbf04a80b40d6f47fee36b4a51c1b38f8771e/extension/data/modules/config.js#L593) and [domain tagger](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/31eb26965cd8f7ad4cf096df232c9ed3569358d6/extension/data/modules/domaintagger.js#L259).

**Comment by Geo1088** [comment]
This will be interesting because apparently the default UN colors are stored as color names instead of hex codes. We'll have to find a way to parse those colors there. (dunno if this also applies to domain tagging, haven't tested thoroughly)

**Comment by creesch** [comment]
I already fixed this in the redesign. You can backport that code.

**Comment by Geo1088** [comment]
Fixed in 311a465c174753e42b59d77ec3af1dc3c263edb1
