### ISSUE TITLE
Modqueue bug

### ISSUE THREAD

**Issue by mootmah** [toolbox-team/reddit-moderator-toolbox#858]
The modqueue is showing an inappropriate kitteh. If one of my modded subs has a clean queue, the multiqueue looks like this: https://i.imgur.com/NEaGcIy.png. The items behind the image are not clickable.

**Comment by creesch** [comment]
Hi, thank you for reporting this. please post issues for the redesign version on /r/tb_redesign. 

I am closing this issue in favor of [this one](https://github.com/toolbox-team/reddit-moderator-toolbox-redesign/issues/17) which is attached to the correct repository.
