### ISSUE TITLE
Add night mode for "0 messages" box in New Mod Mail Pro

### ISSUE THREAD

**Issue by ray13eezy** [toolbox-team/reddit-moderator-toolbox#869]
When opening New Mod Mail with the night mode checkbox enabled, everything looks great EXCEPT for if there are no messages in the folder you are viewing, in which case you are greeted the standard white box that looks like the same whether you are in night mode or not.

**Comment by Geo1088** [comment]
What browser are you using? Nightmode is implemented differently in Firefox and other browsers; I think I see the issue in the Firefox version but just want to confirm that that's what you're using.

**Comment by ray13eezy** [comment]
Yeah I am using Firefox. I did not try any other browsers.

**Comment by Geo1088** [comment]
Sweet, this is fixed by commit 3295b168c76c53b8f0e236bfc0a3b7ac8d19e680 then. Will be in the next release.
