### ISSUE TITLE
The usernotes storage may need a redesign

### ISSUE THREAD

**Issue by fungiboletus** [toolbox-team/reddit-moderator-toolbox#870]
First, thanks to the toolbox-team for their work. This extension is very useful.

I have some comments about the usernotes storage. From what I understood in the current situation all usernotes are stored together in a reddit wiki page (as a JSON compressed with the  DEFLATE/gzip algorithm, encoded as base64).

On the subreddits I moderate, this raises some issues : 

 * We reached the maximum page size allowed by reddit on the usernotes : 512kb.
 * Each time we create / delete / update a note, we have to download and uploads all the notes.
 * We cannot delete wiki revisions, so we cannot really delete usernotes.

The last issue raises some privacy concerns. Our users requested the possibility to remove the notes related to their reddit account, according to the GDPR. It would be very nice to have the possibility to do so.

**Comment by Geo1088** [comment]
Re: that last bit, I don't believe usernotes are actionable under GDPR as they are not information that person put on the site, but information a mod recorded about them, which isn't really "personal data." Also, it's Reddit's responsibility to handle GDPR requests, not yours. In any case, the data will stay sufficiently private as long as you don't make your usernotes wiki public and you're respondible with who mods your subreddit. However, if it's really necessary, I'm pretty sure you can go through the admins to have a page's history pruned.

**Comment by creesch** [comment]
Yeah I am fairly sure GDPR does not apply here as it is mod stored meta data not linked by reddit to a user. I am going to close this issue as it conflates several things together and I am about 99% sure there are issues already about storage.
