### ISSUE TITLE
further improve frontend api event handling.

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#9]
_From @creesch on August 23, 2017 16:59_

Context: https://github.com/Geo1088/reddit-moderator-toolbox/pull/2#issuecomment-324379749 

> One thing that this doesn't (yet) do is information handling, I talked about it a bit on irc yesterday where I floated the idea of creating a toolbox wrapper in the container where the data is also kept. I'd like your thoughts about that. 
> 
> So tblistener would receive the below data
> 
> ```json
> {
> 	"className": "s4tft2m-2 dQciYQ",
> 	"type": "postAuthor",
> 	"data": {
> 		"author": "creesch",
> 		"score": 49,
> 		"voteState": 1
> 	}
> }
> ```
> 
> And then in the container create something like 
> 
> ```html
> <span class="tb-container-wrapper"  data-type="postAuthor" data-author="creesch" data-score="49" data-votestate="1"></span>
> ```
> 
> Before passing on the event so that modules have the wrapper to do their things in and already have the data stored for other future usage.
> 
> The pro side of this is that you don't need each module to handle this for their own use case and that it allows a sort of 'safe haven' for toolbox elements where interference by RES and other extensions is less likely. 
> 
> A possible con is that we will not need to act on each container, handling like this does write to the DOM on every event we receive though possibly impacting performance negatively. 

_Copied from original issue: Geo1088/reddit-moderator-toolbox#6_

**Comment by creesch** [comment]
I think we did this already... but then with the jquery data attribute possibly? Need to look into it.

**Comment by Geo1088** [comment]
This is handled with `.data()` and is already used in several places. I think this is a good enough situation to use `.data()` instead of `.attr('data-*')` because then we avoid having to serialize to JSON and write to the DOM. Closing.
