### ISSUE TITLE
Feature request: add a setting to automatically archive comment removal modmail messages

### ISSUE THREAD

**Issue by vitosamson** [toolbox-team/reddit-moderator-toolbox#90]
This was requested in /r/toolbox [here](https://www.reddit.com/r/toolbox/comments/5ecqfk/feature_request_the_removal_reasons_prompt_should/) and [here](https://www.reddit.com/r/toolbox/comments/5t2t8q/feature_request_automatically_archive_modmail/).

The "Send removal reasons as subreddit" setting currently warns "Note: these will appear in modmail and potentially clutter it up.", which feature would help avoid.

A couple questions:
  - Is it possible to enforce this setting (and the send as sub setting) for all mods in a subreddit?
  - If a subreddit is still using the old mod mail, is it better to have this setting be a noop or to hit the /archive endpoint anyway? The endpoint returns 404 if the conversationId is invalid.
  - Does toolbox currently contain any util for determining if a subreddit is on the new mod mail? (Aside from checking for the `mod.reddit.com` hostname, which only works when the user is checking modmail)

I'm happy to open a PR for this feature.

**Comment by Geo1088** [comment]
blocked on #117
