### ISSUE TITLE
[Feature Request] Entry for Toolbox removal reasons in modlog

### ISSUE THREAD

**Issue by UInt2048** [toolbox-team/reddit-moderator-toolbox#927]
When mods using Reddit's native removal reasons use one, it leaves an addremovalreason entry in the modlog.

Could something similar even be possible for Toolbox's removal reasons on Old Reddit?

**Comment by eritbh** [comment]
This is unfortunately not something we can do.

 - The API does not give us access to insert our own arbitrary entries into the mod log.
 - The `addremovalreason` entry is recorded as a side effect of using the native RRs API to leave one of the removal reasons defined in the native config; however we've looked into this in the past, and it's not practical for us to bridge the gap between Toolbox reasons and native reasons while maintaining Toolbox's advanced functionality (leaving multiple reasons, placeholders, dropdowns and text inputs in reasons).
