### ISSUE TITLE
Rework debugging console

### ISSUE THREAD

**Issue by creesch** [toolbox-team/reddit-moderator-toolbox#96]
On discord we discussed reworking the debugging console, I figured I'd make an issue here so it is all documented. 

## Do away with the html console

I rarely use it, it is heavy and cumbersome. I'd like to rework the debug window to just have the controls for console output. 

If it turns out we want a dedicated console I propose we make use of a background page where console messages get send to so we can use the browser console there. 

## Get rid of the eval method

Frankly it is sometimes useful but it is also a security risk that slows down review. 

## Move debug console code to tbDebug.js or something like that.
It currently is a jquery plugin, which is silly. I'd like to make it a proper class in itself that can be called for outputting messages and given filter parameters.

Due to the way logging works in toolbox this is also fairly easy to do. We need to replace all `$.log` instances with the new method of which there aren't a whole lot (around 60) and map the module `self.log` to that as well for initial migration. We can then refine how `self.log` works as well later on.

## Use console.trace in combination with a collapsed group, possibly also add timestamp.
Currently it is impossible to see from where a log function was called. Putting the console message in a collapsed group that includes a console.trace() would give better insights. Example:

```javascript
console.groupCollapsed('[caller]', message);
console.trace()
console.groupEnd()
```

As the headline says, possibly add a timestamp. 

```javascript
console.log(new Date().toISOString());
```

console.log(new Date().toISOString());

## Have various color coded types 

```javascript
console.log('[Caller] %c Error:', 'background-color: #e80303; color: #fff', 'This is a serious error');
```

outputs

![image](https://user-images.githubusercontent.com/2502190/59495203-1b3d9900-8e8f-11e9-8bfc-46780eb535f8.png)

I want to basically mimic native console types but with our own coloring. Doing it like this allows us to filter just toolbox related things. 

## Better filter options 
I'd like to be able to define a variety of filters from toolbox itself. 

- More refined module selection. Currently it is a dropdown, I'd like it to be a selection list so we can show multiple modules at once. 
- Filter on message type.

**Comment by creesch** [comment]
points above are not in order of importance btw.

**Comment by creesch** [comment]
So I might have skipped ahead a bit and written a new log class sort of... 

```javascript
(function () {
    /**
     * The various log types by name and their colors
     */
    const logTypes = {
        debug: {
            color: '#fff',
            background: '#387fa7',
        },
        log: {
            color: '#fff',
            background: '#38a762',
        },
        warn: {
            color: '#fff',
            background: '#ce821a',
        },
        error: {
            color: '#fff',
            background: '#eb3941',
        }
    }

    const filteredCallers = [];
    const filteredTypes = [];

    /**
     * We send the actual console message here. 
     *
     * @private
     */
    function sendToConsole(caller, message) {
        const type = this.toString();

        if(filteredCallers.includes(caller) || filteredTypes.includes(type)) {
            return;
        }
        const typeColors = logTypes[type];
        console.groupCollapsed(`%c[${caller}] ${type}`, `background-color: ${typeColors.background}; color: ${typeColors.color};`, message);
        console.log(new Date().toISOString());
        console.trace();
        console.groupEnd();

    }

    class tbLog {
        constructor() {
            this.debug = sendToConsole.bind('debug');
            this.log = sendToConsole.bind('log');
            this.warn = sendToConsole.bind('warn');
            this.error = sendToConsole.bind('error');
        }

        get currentFilters() {
            return {
                filteredCallers,
                filteredTypes,
            };
        }

        addCallerFilter(caller) {
            if(!filteredCallers.includes(caller)) {
                filteredCallers.push(caller)
            }
        }

        removeCallerFilter(caller) {
            const callerIndex = filteredCallers.indexOf(caller);
            if (callerIndex > -1) {
                filteredCallers.splice(callerIndex, 1);
            }
        }

        addTypeFilter(type) {
            if(!filteredTypes.includes(type)) {
                filteredTypes.push(type)
            }
        }

        removeTypeFilter(type) {
            const typeIndex = filteredTypes.indexOf(type);
            if (typeIndex > -1) {
                filteredTypes.splice(typeIndex, 1);
            }
        }
    }
    window.tbLog = new tbLog();
})();
```

**Comment by Geo1088** [comment]
Some issues I have with that:

- I don't like having to explicitly pass a caller to the function
- I want to be able to pass an arbitrary amount of arguments to the function
- I don't like using singleton classes where object literals will work :P

Here's my proposed solution:

```js
(function () {
	/**
	 * The various log types by name and their colors
	 */
	const logTypes = {
        debug: {
            color: '#fff',
            background: '#387fa780',
        },
        log: {
            color: '#fff',
            background: '#38a76280',
        },
        warn: {
            color: '#fff',
            background: '#ce821a80',
        },
        error: {
            color: '#fff',
            background: '#eb394180',
        },
    };

	// it's also slightly easier to record these as objects rather than arrays
	const filteredTypes = {};
	const filteredCallers = {};

	/**
	 * @private
	 * Internal function to execute a log of a certain type.
	 * @param {string} type The name of the log type to use
	 * @param {...any} args Arbitrary content passed through to the console 
	function log(type, ...args) {
		// calling module is bound to `this` if there is one
		const moduleName = this ? this.shortname : 'unknown';
		// If the calling module or log type is filtered, do nothing
		if (filteredTypes[type] || filteredCallers[moduleName]) {
			return;
		}
		const {color, background} = logTypes[type];

		console.groupCollapsed(
			// first part of the message line
			`[${moduleName}] %c${levelName}`,
			// styles for the type name
			`color: ${color}; background: ${background}`,
			// the rest of the arguments are passed through unmodified
			...stuff
		);

		// Combine the timestamp with the traceback for simplicity
		console.trace(`Called at: ${new Date.toISOString()}`);
		console.groupEnd();
	}

	/**
	 * Creates a logger object with a given module as its caller.
	 * @param {object} module The module acting as the caller
	 */
	function tbLog (module) {
		// Create a new object
		const obj = {};
		// The object gets a function for every log type
		for (const type in logTypes) {
			// `this` arg is the calling module, first arg is the log type
			obj[type] = log.bind(module, type);
		}
		return obj;
	}

	// This is a bit of cleverness - we make a logger with no caller, and then
	// assign that logger's properties to the function, so it can be used as an
	// object as well
	Object.assign(tbLog, tbLog());

	// Finally, we define the functions to add/remove filtered callers/log types
	tbLog.addCallerFilter (shortname) {
		filteredCallers[shortname] = true;
	}
	tbLog.removeCallerFilter (shortname) {
		delete filteredCallers[shortname];
	}
	tbLog.addTypeFilter (type) {
		filteredTypes[type] = true;
	}
	tbLog.removeTypeFilter (type) {
		delete filteredTypes[type];
	}

	// Huzzah!
	window.tbLog = tbLog;
})();
```

With this code, we can then do intuitive caller-less logs:

```js
tbLog.log('Some stuff', 42, {an: {object: 'literal'}});
//=> [unknown] log Some stuff 42 Object { key: "value" }
``

Additionally, we can simplify the logging portion of the module constructor by replacing [these lines](https://github.com/toolbox-team/reddit-moderator-toolbox/blob/master/extension/data/tbmodule.js#L1017-L1025) with:

```js
Object.assign(this, tbLog(this));
```

which means we can then do the following from within modules:

```js
self.log('Stuff');
self.error('Oh we did a bad');
//=> [moduleShortname] log Stuff
//=> [moduleShortname] log Oh we did a bad
```

**Comment by creesch** [comment]
I am fine with this as well except for two small things: 

1. I want timestamps as a console line as that is just easier to parse in how the console displays them. 
2. Your proposal is missing the `currentFilters` getter which I suspect we want. 

Other than that it looks good to me.

**Comment by creesch** [comment]
Like I said in discord, third thing: 

- naming it `moduleName` isn't correct, small semantic thing but important anyway as we have more than just modules.

**Comment by Geo1088** [comment]
Addressed both of those concerns. I replaced the `currentFilters` getter with transparent properties to access `filteredCallers` and `filteredTypes` directly - don't think there's any practical reason to wrap them in an object.

**Comment by Geo1088** [comment]
Initial work for this pushed in c3ec17f. The old browser console and (I think) all related code has been removed.

Still TODO on this issue:

- [x] Filter debug logs unless the debug mode setting is enabled
- [ ] Build interface for filtering settings
- [ ] Ensure that filter preferences are maintained in a persistent setting
